import type { MenuItem, MenuCategory, MenuCategoryGroup } from "./types";

  export const MENU_ITEMS: MenuItem[] = [
  // ─── SOUPS ───
  { id: "m1", name: "Mushroom Cappuccino Soup", category: "food-soups", group: "food", price: 228, unit: "each", isAlcohol: false, available: true, isVeg: true, costPrice: 30, floor: "rooftop" },
  { id: "m2", name: "Tomato Basil Soup", category: "food-soups", group: "food", price: 185, unit: "each", isAlcohol: false, available: true, isVeg: true, costPrice: 15, floor: "rooftop" },
  { id: "m3", name: "Manchow Soup - Veg", category: "food-soups", group: "food", price: 185, unit: "each", isAlcohol: false, available: true, isVeg: true, costPrice: 18, floor: "2nd-floor" },
  { id: "m4", name: "Manchow Soup - Chicken", category: "food-soups", group: "food", price: 228, unit: "each", isAlcohol: false, available: true, isVeg: false, costPrice: 33, floor: "2nd-floor" },
  // ─── SALADS ───
  { id: "m5", name: "Indian Farmhouse Salad", category: "food-salads", group: "food", price: 235, unit: "each", isAlcohol: false, available: true, isVeg: true, costPrice: 19, floor: "2nd-floor" },
  { id: "m6", name: "Caesar Sald Veg", category: "food-salads", group: "food", price: 285, unit: "each", isAlcohol: false, available: true, isVeg: true, costPrice: 38, floor: "rooftop" },
  { id: "m7", name: "Caesar Salad Chicken", category: "food-salads", group: "food", price: 299, unit: "each", isAlcohol: false, available: true, isVeg: false, costPrice: 85, floor: "rooftop" },
  { id: "m8", name: "Watermelon Feta Salad", category: "food-salads", group: "food", price: 285, unit: "each", isAlcohol: false, available: true, isVeg: true, costPrice: 40, floor: "rooftop" },
  { id: "m9", name: "Booster Salad Veg", category: "food-salads", group: "food", price: 235, unit: "each", isAlcohol: false, available: true, isVeg: true, costPrice: 38, floor: "rooftop" },
  { id: "m10", name: "Booster Salad Chicken", category: "food-salads", group: "food", price: 299, unit: "each", isAlcohol: false, available: true, isVeg: false, costPrice: 54, floor: "rooftop" },
  // ─── BAR BITES & CHAAT ───
  { id: "m11", name: "Salted French Fries", category: "food-bar-bites", group: "food", price: 235, unit: "each", isAlcohol: false, available: true, isVeg: true, costPrice: 35, floor: "rooftop" },
  { id: "m12", name: "Peri Peri French Fries", category: "food-bar-bites", group: "food", price: 285, unit: "each", isAlcohol: false, available: true, isVeg: true, costPrice: 43, floor: "rooftop" },
  { id: "m13", name: "Corn Salt & Pepper", category: "food-bar-bites", group: "food", price: 295, unit: "each", isAlcohol: false, available: true, isVeg: true, costPrice: 43, floor: "2nd-floor" },
  { id: "m14", name: "Noughty Nutties", category: "food-bar-bites", group: "food", price: 299, unit: "each", isAlcohol: false, available: true, isVeg: true, costPrice: 43, floor: "2nd-floor" },
  { id: "m15", name: "Bbq Style Cajun Potato", category: "food-bar-bites", group: "food", price: 299, unit: "each", isAlcohol: false, available: true, isVeg: true, costPrice: 43, floor: "rooftop" },
  { id: "m16", name: "Peanut Masala", category: "food-bar-bites", group: "food", price: 299, unit: "each", isAlcohol: false, available: true, isVeg: true, costPrice: 38, floor: "2nd-floor" },
  { id: "m17", name: "Egg Pakoda", category: "food-bar-bites", group: "food", price: 199, unit: "each", isAlcohol: false, available: true, isVeg: false, floor: "2nd-floor" },
  { id: "m18", name: "Egg Bhurji", category: "food-bar-bites", group: "food", price: 199, unit: "each", isAlcohol: false, available: true, isVeg: false, floor: "2nd-floor" },
  { id: "m19", name: "Boild Egg", category: "food-bar-bites", group: "food", price: 149, unit: "each", isAlcohol: false, available: true, isVeg: false, floor: "2nd-floor" },
  { id: "m20", name: "Chicken Tikka Chick Peas Chat", category: "food-bar-bites", group: "food", price: 329, unit: "each", isAlcohol: false, available: true, isVeg: false, costPrice: 85, floor: "2nd-floor" },
  { id: "m21", name: "Nipattu Avocado Chat", category: "food-bar-bites", group: "food", price: 329, unit: "each", isAlcohol: false, available: true, isVeg: true, costPrice: 85, floor: "2nd-floor" },
  // ─── CHARGRILLED APPETIZERS ───
  { id: "m22", name: "Harissa Paneer Tikka", category: "food-chargrilled", group: "food", price: 410, unit: "each", isAlcohol: false, available: true, isVeg: true, costPrice: 90, floor: "2nd-floor" },
  { id: "m23", name: "Chimichuri Paneer Tikka", category: "food-chargrilled", group: "food", price: 405, unit: "each", isAlcohol: false, available: true, isVeg: true, costPrice: 90, floor: "2nd-floor" },
  { id: "m24", name: "Zafran Malai Brocolli", category: "food-chargrilled", group: "food", price: 375, unit: "each", isAlcohol: false, available: true, isVeg: true, costPrice: 99, floor: "2nd-floor" },
  { id: "m25", name: "Tahina Stuffed Mushroom", category: "food-chargrilled", group: "food", price: 401, unit: "each", isAlcohol: false, available: true, isVeg: true, costPrice: 90, floor: "2nd-floor" },
  { id: "m26", name: "Guntur Chicken Tikka", category: "food-chargrilled", group: "food", price: 405, unit: "each", isAlcohol: false, available: true, isVeg: false, costPrice: 100, floor: "2nd-floor" },
  { id: "m27", name: "Asian Chicken Tikka", category: "food-chargrilled", group: "food", price: 405, unit: "each", isAlcohol: false, available: true, isVeg: false, costPrice: 100, floor: "2nd-floor" },
  { id: "m28", name: "Balsamic Pepper Chicken Tikka", category: "food-chargrilled", group: "food", price: 405, unit: "each", isAlcohol: false, available: true, isVeg: false, costPrice: 100, floor: "2nd-floor" },
  { id: "m29", name: "Mexicon Chilli Cheese Kabab", category: "food-chargrilled", group: "food", price: 405, unit: "each", isAlcohol: false, available: true, isVeg: false, costPrice: 110, floor: "2nd-floor" },
  { id: "m30", name: "Sole Fish Tikka", category: "food-chargrilled", group: "food", price: 459, unit: "each", isAlcohol: false, available: true, isVeg: false, costPrice: 115, floor: "2nd-floor" },
  { id: "m31", name: "Mutton Seekh Kabab With Pita", category: "food-chargrilled", group: "food", price: 499, unit: "each", isAlcohol: false, available: true, isVeg: false, costPrice: 175, floor: "2nd-floor" },
  { id: "m32", name: "Moilee Prawns Tandoori", category: "food-chargrilled", group: "food", price: 565, unit: "each", isAlcohol: false, available: true, isVeg: false, costPrice: 175, floor: "2nd-floor" },
  { id: "m33", name: "Pindiwala Bhatti Da Murgh", category: "food-chargrilled", group: "food", price: 475, unit: "each", isAlcohol: false, available: true, isVeg: false, costPrice: 185, floor: "2nd-floor" },
  { id: "m34", name: "Peri Peri Tandoori Wings", category: "food-chargrilled", group: "food", price: 401, unit: "each", isAlcohol: false, available: true, isVeg: false, costPrice: 95, floor: "2nd-floor" },
  { id: "m35", name: "Murgh Malai Tikka", category: "food-chargrilled", group: "food", price: 399, unit: "each", isAlcohol: false, available: true, isVeg: false, floor: "2nd-floor" },
  // ─── PLATTERS ───
  { id: "m36", name: "Veg Platters", category: "food-platters", group: "food", price: 1499, unit: "each", isAlcohol: false, available: true, isVeg: true, floor: "2nd-floor" },
  { id: "m37", name: "Nonveg Platters", category: "food-platters", group: "food", price: 2299, unit: "each", isAlcohol: false, available: true, isVeg: false, floor: "2nd-floor" },
  // ─── ORIENTAL ───
  { id: "m38", name: "Togorasi Lotus Stem Chips", category: "food-oriental", group: "food", price: 325, unit: "each", isAlcohol: false, available: true, isVeg: true, costPrice: 75, floor: "2nd-floor" },
  { id: "m39", name: "Tangy Mushroom", category: "food-oriental", group: "food", price: 299, unit: "each", isAlcohol: false, available: true, isVeg: true, costPrice: 85, floor: "2nd-floor" },
  { id: "m40", name: "Cheese Wonton", category: "food-oriental", group: "food", price: 401, unit: "each", isAlcohol: false, available: true, isVeg: true, costPrice: 95, floor: "2nd-floor" },
  { id: "m41", name: "Korean Chilli Potato", category: "food-oriental", group: "food", price: 299, unit: "each", isAlcohol: false, available: true, isVeg: true, costPrice: 65, floor: "2nd-floor" },
  { id: "m42", name: "Roasted Brussels And Tofu", category: "food-oriental", group: "food", price: 401, unit: "each", isAlcohol: false, available: true, isVeg: true, costPrice: 105, floor: "2nd-floor" },
  { id: "m43", name: "Stir Fried Mushroom And Broccoli With Bok Choy", category: "food-oriental", group: "food", price: 401, unit: "each", isAlcohol: false, available: true, isVeg: true, costPrice: 105, floor: "2nd-floor" },
  { id: "m44", name: "Schezwan Cottage Cheese", category: "food-oriental", group: "food", price: 349, unit: "each", isAlcohol: false, available: true, isVeg: true, costPrice: 95, floor: "2nd-floor" },
  { id: "m45", name: "Egg Chilli", category: "food-oriental", group: "food", price: 249, unit: "each", isAlcohol: false, available: true, isVeg: false, floor: "2nd-floor" },
  { id: "m46", name: "Chicken Tikka Chilli", category: "food-oriental", group: "food", price: 401, unit: "each", isAlcohol: false, available: true, isVeg: false, costPrice: 100, floor: "2nd-floor" },
  { id: "m47", name: "Drums Of Heaven", category: "food-oriental", group: "food", price: 399, unit: "each", isAlcohol: false, available: true, isVeg: false, costPrice: 100, floor: "2nd-floor" },
  { id: "m48", name: "Beer Chilli Chicken", category: "food-oriental", group: "food", price: 401, unit: "each", isAlcohol: false, available: true, isVeg: false, costPrice: 100, floor: "2nd-floor" },
  { id: "m49", name: "Steamed Fish", category: "food-oriental", group: "food", price: 409, unit: "each", isAlcohol: false, available: true, isVeg: false, costPrice: 120, floor: "2nd-floor" },
  { id: "m50", name: "Chicken Techha", category: "food-oriental", group: "food", price: 399, unit: "each", isAlcohol: false, available: true, isVeg: false, costPrice: 100, floor: "2nd-floor" },
  { id: "m51", name: "Asian Style Lemon Chicken With Long Beans", category: "food-oriental", group: "food", price: 399, unit: "each", isAlcohol: false, available: true, isVeg: false, costPrice: 105, floor: "2nd-floor" },
  { id: "m52", name: "Chilli Cilantro Mushroom Bao", category: "food-oriental", group: "food", price: 375, unit: "each", isAlcohol: false, available: true, isVeg: true, costPrice: 99, floor: "2nd-floor" },
  { id: "m53", name: "Korean Chicken Bao", category: "food-oriental", group: "food", price: 401, unit: "each", isAlcohol: false, available: true, isVeg: false, costPrice: 105, floor: "2nd-floor" },
  { id: "m54", name: "Tempura Tofu Bao", category: "food-oriental", group: "food", price: 399, unit: "each", isAlcohol: false, available: true, isVeg: false, costPrice: 110, floor: "2nd-floor" },
  { id: "m55", name: "Veg Gyoza", category: "food-oriental", group: "food", price: 299, unit: "each", isAlcohol: false, available: true, isVeg: true, costPrice: 85, floor: "2nd-floor" },
  { id: "m56", name: "Chicken Gyoza", category: "food-oriental", group: "food", price: 329, unit: "each", isAlcohol: false, available: true, isVeg: false, costPrice: 95, floor: "2nd-floor" },
  { id: "m57", name: "Veg Chilli Oil Dumpling", category: "food-oriental", group: "food", price: 399, unit: "each", isAlcohol: false, available: true, isVeg: true, costPrice: 99, floor: "2nd-floor" },
  { id: "m58", name: "Spicy Celery Chicken Dimsum", category: "food-oriental", group: "food", price: 405, unit: "each", isAlcohol: false, available: true, isVeg: false, costPrice: 99, floor: "2nd-floor" },
  // ─── INTERNATIONAL ───
  { id: "m59", name: "Corn Ribs", category: "food-international", group: "food", price: 290, unit: "each", isAlcohol: false, available: true, isVeg: true, costPrice: 29, floor: "rooftop" },
  { id: "m60", name: "Nachos Veg", category: "food-international", group: "food", price: 299, unit: "each", isAlcohol: false, available: true, isVeg: true, costPrice: 70, floor: "rooftop" },
  { id: "m61", name: "Crisy Fried Onion Ring", category: "food-international", group: "food", price: 285, unit: "each", isAlcohol: false, available: true, isVeg: true, costPrice: 30, floor: "rooftop" },
  { id: "m62", name: "Tex -mex Cheese Poppers", category: "food-international", group: "food", price: 401, unit: "each", isAlcohol: false, available: true, isVeg: true, costPrice: 95, floor: "rooftop" },
  { id: "m63", name: "Peri Peri Grilled Paneer", category: "food-international", group: "food", price: 401, unit: "each", isAlcohol: false, available: true, isVeg: true, costPrice: 95, floor: "rooftop" },
  { id: "m64", name: "Babycorn Fritters", category: "food-international", group: "food", price: 299, unit: "each", isAlcohol: false, available: true, isVeg: true, costPrice: 55, floor: "rooftop" },
  { id: "m65", name: "Paneer Fritters", category: "food-international", group: "food", price: 399, unit: "each", isAlcohol: false, available: true, isVeg: true, costPrice: 95, floor: "rooftop" },
  { id: "m66", name: "Cheese Garlic Bread", category: "food-international", group: "food", price: 285, unit: "each", isAlcohol: false, available: true, isVeg: true, costPrice: 33, floor: "rooftop" },
  { id: "m67", name: "Pull Apart Cheese Bread", category: "food-international", group: "food", price: 299, unit: "each", isAlcohol: false, available: true, isVeg: true, costPrice: 55, floor: "rooftop" },
  { id: "m68", name: "Butter Garlic Mushroom & Brocolli", category: "food-international", group: "food", price: 349, unit: "each", isAlcohol: false, available: true, isVeg: true, costPrice: 90, floor: "rooftop" },
  { id: "m69", name: "Nachos Chicken", category: "food-international", group: "food", price: 349, unit: "each", isAlcohol: false, available: true, isVeg: false, costPrice: 75, floor: "rooftop" },
  { id: "m70", name: "Avocado Ricotta Chicken Crostini", category: "food-international", group: "food", price: 319, unit: "each", isAlcohol: false, available: true, isVeg: false, floor: "rooftop" },
  { id: "m71", name: "Hot & Spicy Chicken Wings", category: "food-international", group: "food", price: 401, unit: "each", isAlcohol: false, available: true, isVeg: false, costPrice: 90, floor: "rooftop" },
  { id: "m72", name: "Chicken Popcorn", category: "food-international", group: "food", price: 349, unit: "each", isAlcohol: false, available: true, isVeg: false, costPrice: 99, floor: "rooftop" },
  { id: "m73", name: "Crunchy Threaded Chicken", category: "food-international", group: "food", price: 349, unit: "each", isAlcohol: false, available: true, isVeg: false, costPrice: 100, floor: "rooftop" },
  { id: "m74", name: "Butter Garlic Prawns & Brocolli", category: "food-international", group: "food", price: 459, unit: "each", isAlcohol: false, available: true, isVeg: false, costPrice: 195, floor: "rooftop" },
  { id: "m75", name: "Fish & Chips", category: "food-international", group: "food", price: 519, unit: "each", isAlcohol: false, available: true, isVeg: false, costPrice: 185, floor: "rooftop" },
  { id: "m76", name: "Grilled Chicken With Mushroom Pepper Sauce", category: "food-international", group: "food", price: 401, unit: "each", isAlcohol: false, available: true, isVeg: true, costPrice: 175, floor: "rooftop" },
  { id: "m77", name: "Grilled Fish With Lemon Butter Sauce", category: "food-international", group: "food", price: 449, unit: "each", isAlcohol: false, available: true, isVeg: false, costPrice: 175, floor: "rooftop" },
  // ─── PASTA & PIZZA ───
  { id: "m78", name: "Alfredo Sauce Penne Pasta Veg", category: "food-pasta-pizza", group: "food", price: 509, unit: "each", isAlcohol: false, available: true, isVeg: true, costPrice: 85, floor: "rooftop" },
  { id: "m79", name: "Alfredo Sauce Penne Pasta Chicken", category: "food-pasta-pizza", group: "food", price: 509, unit: "each", isAlcohol: false, available: true, isVeg: false, costPrice: 110, floor: "rooftop" },
  { id: "m80", name: "Arrabiata Sauce Penne Pasta Veg", category: "food-pasta-pizza", group: "food", price: 399, unit: "each", isAlcohol: false, available: true, isVeg: true, costPrice: 85, floor: "rooftop" },
  { id: "m81", name: "Arrabiata Sauce Penne Pasta Chicken", category: "food-pasta-pizza", group: "food", price: 509, unit: "each", isAlcohol: false, available: true, isVeg: false, costPrice: 110, floor: "rooftop" },
  { id: "m82", name: "Spaghetti Aglio E Olio Veg", category: "food-pasta-pizza", group: "food", price: 399, unit: "each", isAlcohol: false, available: true, isVeg: true, costPrice: 85, floor: "rooftop" },
  { id: "m83", name: "Spaghetti Aglio E Olio Chicken", category: "food-pasta-pizza", group: "food", price: 509, unit: "each", isAlcohol: false, available: true, isVeg: false, costPrice: 110, floor: "rooftop" },
  { id: "m84", name: "Spaghetti Pesto Sauce Veg", category: "food-pasta-pizza", group: "food", price: 399, unit: "each", isAlcohol: false, available: true, isVeg: true, costPrice: 85, floor: "rooftop" },
  { id: "m85", name: "Spaghetti Pesto Sauce Chicken", category: "food-pasta-pizza", group: "food", price: 509, unit: "each", isAlcohol: false, available: true, isVeg: false, costPrice: 110, floor: "rooftop" },
  { id: "m86", name: "Italian Veggie Pizza", category: "food-pasta-pizza", group: "food", price: 516, unit: "each", isAlcohol: false, available: true, isVeg: true, floor: "rooftop" },
  { id: "m87", name: "Clasic Margarita", category: "food-pasta-pizza", group: "food", price: 509, unit: "each", isAlcohol: false, available: true, isVeg: true, floor: "rooftop" },
  { id: "m88", name: "Mushroom Corn Pizza", category: "food-pasta-pizza", group: "food", price: 516, unit: "each", isAlcohol: false, available: true, isVeg: true, floor: "rooftop" },
  { id: "m89", name: "Fiery Chicken Pizza", category: "food-pasta-pizza", group: "food", price: 399, unit: "each", isAlcohol: false, available: true, isVeg: false, floor: "rooftop" },
  { id: "m90", name: "Bbq Chicken Pizza", category: "food-pasta-pizza", group: "food", price: 629, unit: "each", isAlcohol: false, available: true, isVeg: false, floor: "rooftop" },
  { id: "m91", name: "Fiery Chicken Pizza", category: "food-pasta-pizza", group: "food", price: 629, unit: "each", isAlcohol: false, available: true, isVeg: false, floor: "rooftop" },
  { id: "m92", name: "Pesto Seafood Pizza", category: "food-pasta-pizza", group: "food", price: 680, unit: "each", isAlcohol: false, available: true, isVeg: false, floor: "rooftop" },
  // ─── COASTAL ───
  { id: "m93", name: "Ghee Roast Mushroom", category: "food-coastal", group: "food", price: 349, unit: "each", isAlcohol: false, available: true, isVeg: true, costPrice: 90, floor: "2nd-floor" },
  { id: "m94", name: "Ghee Roast Paneer", category: "food-coastal", group: "food", price: 401, unit: "each", isAlcohol: false, available: true, isVeg: true, costPrice: 110, floor: "2nd-floor" },
  { id: "m95", name: "Ghee Roast Egg", category: "food-coastal", group: "food", price: 305, unit: "each", isAlcohol: false, available: true, isVeg: true, floor: "2nd-floor" },
  { id: "m96", name: "Ghee Roast Chicken", category: "food-coastal", group: "food", price: 405, unit: "each", isAlcohol: false, available: true, isVeg: false, costPrice: 110, floor: "2nd-floor" },
  { id: "m97", name: "Ghee Roast Mutton", category: "food-coastal", group: "food", price: 519, unit: "each", isAlcohol: false, available: true, isVeg: false, costPrice: 185, floor: "2nd-floor" },
  { id: "m98", name: "Ghee Roast Prawns", category: "food-coastal", group: "food", price: 559, unit: "each", isAlcohol: false, available: true, isVeg: false, costPrice: 165, floor: "2nd-floor" },
  { id: "m99", name: "Natti Style Pepper Fry Mushroom", category: "food-coastal", group: "food", price: 401, unit: "each", isAlcohol: false, available: true, isVeg: true, costPrice: 85, floor: "2nd-floor" },
  { id: "m100", name: "Natti Style Pepper Fry Paneer", category: "food-coastal", group: "food", price: 401, unit: "each", isAlcohol: false, available: true, isVeg: true, costPrice: 90, floor: "2nd-floor" },
  { id: "m101", name: "Natti Style Egg Pepper Dry", category: "food-coastal", group: "food", price: 305, unit: "each", isAlcohol: false, available: true, isVeg: true, floor: "2nd-floor" },
  { id: "m102", name: "Natti Style Pepper Fry Chicken", category: "food-coastal", group: "food", price: 459, unit: "each", isAlcohol: false, available: true, isVeg: false, costPrice: 90, floor: "2nd-floor" },
  { id: "m103", name: "Natti Style Pepper Fry Mutton", category: "food-coastal", group: "food", price: 519, unit: "each", isAlcohol: false, available: true, isVeg: false, costPrice: 160, floor: "2nd-floor" },
  { id: "m104", name: "Natti Style Pepper Fry Prawns", category: "food-coastal", group: "food", price: 569, unit: "each", isAlcohol: false, available: true, isVeg: false, costPrice: 145, floor: "2nd-floor" },
  { id: "m105", name: "Mushroom Urval", category: "food-coastal", group: "food", price: 401, unit: "each", isAlcohol: false, available: true, isVeg: true, costPrice: 85, floor: "2nd-floor" },
  { id: "m106", name: "Paneer Urval", category: "food-coastal", group: "food", price: 401, unit: "each", isAlcohol: false, available: true, isVeg: true, costPrice: 90, floor: "2nd-floor" },
  { id: "m107", name: "Chicken Urval", category: "food-coastal", group: "food", price: 405, unit: "each", isAlcohol: false, available: true, isVeg: false, costPrice: 95, floor: "2nd-floor" },
  { id: "m108", name: "Mutton Urval", category: "food-coastal", group: "food", price: 519, unit: "each", isAlcohol: false, available: true, isVeg: false, costPrice: 145, floor: "2nd-floor" },
  { id: "m109", name: "Pranws Urval", category: "food-coastal", group: "food", price: 519, unit: "each", isAlcohol: false, available: true, isVeg: false, costPrice: 165, floor: "2nd-floor" },
  { id: "m110", name: "Cashew Curry Leaf Paneer", category: "food-coastal", group: "food", price: 401, unit: "each", isAlcohol: false, available: true, isVeg: true, costPrice: 85, floor: "2nd-floor" },
  { id: "m111", name: "Cashew Curry Leaf Chicken", category: "food-coastal", group: "food", price: 401, unit: "each", isAlcohol: false, available: true, isVeg: false, costPrice: 90, floor: "2nd-floor" },
  { id: "m112", name: "Anjal Fish / Kane Fish / Pomfret", category: "food-coastal", group: "food", price: 0, unit: "each", isAlcohol: false, available: true, isVeg: true, floor: "both" },
  // ─── MAIN COURSE ───
  { id: "m113", name: "Double Dal Tadka", category: "food-mains", group: "food", price: 239, unit: "each", isAlcohol: false, available: true, isVeg: true, costPrice: 28, floor: "2nd-floor" },
  { id: "m114", name: "Sabji Meloni", category: "food-mains", group: "food", price: 299, unit: "each", isAlcohol: false, available: true, isVeg: true, costPrice: 45, floor: "2nd-floor" },
  { id: "m115", name: "Kadai Paneer With Kamal Kakdi", category: "food-mains", group: "food", price: 401, unit: "each", isAlcohol: false, available: true, isVeg: true, costPrice: 90, floor: "2nd-floor" },
  { id: "m116", name: "Paneer Khurchan", category: "food-mains", group: "food", price: 401, unit: "each", isAlcohol: false, available: true, isVeg: true, costPrice: 90, floor: "2nd-floor" },
  { id: "m117", name: "Lasooni Palak Paneer", category: "food-mains", group: "food", price: 401, unit: "each", isAlcohol: false, available: true, isVeg: true, costPrice: 90, floor: "2nd-floor" },
  { id: "m118", name: "Mushroom Chicken Ghotala", category: "food-mains", group: "food", price: 401, unit: "each", isAlcohol: false, available: true, isVeg: false, costPrice: 95, floor: "2nd-floor" },
  { id: "m119", name: "Hod Special Chicken Curry", category: "food-mains", group: "food", price: 401, unit: "each", isAlcohol: false, available: true, isVeg: false, costPrice: 85, floor: "2nd-floor" },
  { id: "m120", name: "Murgh Patiyala", category: "food-mains", group: "food", price: 401, unit: "each", isAlcohol: false, available: true, isVeg: false, costPrice: 90, floor: "2nd-floor" },
  { id: "m121", name: "Kadai Chicken With Kamal Kakdi", category: "food-mains", group: "food", price: 401, unit: "each", isAlcohol: false, available: true, isVeg: false, costPrice: 90, floor: "2nd-floor" },
  { id: "m122", name: "Palak Chicken", category: "food-mains", group: "food", price: 401, unit: "each", isAlcohol: false, available: true, isVeg: false, costPrice: 90, floor: "2nd-floor" },
  { id: "m123", name: "Rogni Raiwala Meat", category: "food-mains", group: "food", price: 516, unit: "each", isAlcohol: false, available: true, isVeg: false, costPrice: 135, floor: "2nd-floor" },
  { id: "m124", name: "Manglorean Style Fish Curry", category: "food-mains", group: "food", price: 649, unit: "each", isAlcohol: false, available: true, isVeg: false, floor: "2nd-floor" },
  { id: "m125", name: "Manglorean Style Pomfret Fish", category: "food-mains", group: "food", price: 649, unit: "each", isAlcohol: false, available: true, isVeg: false, floor: "2nd-floor" },
  { id: "m126", name: "Manglorean Style Kane Fish Curry", category: "food-mains", group: "food", price: 399, unit: "each", isAlcohol: false, available: true, isVeg: false, floor: "2nd-floor" },
  { id: "m127", name: "Silken Tofu Cubs Vibrant And Spicy Schezwan Sauce With Jasmine Rice", category: "food-mains", group: "food", price: 419, unit: "each", isAlcohol: false, available: true, isVeg: true, floor: "both" },
  { id: "m128", name: "Massaman Curry Veg With Jasmine Rice", category: "food-mains", group: "food", price: 401, unit: "each", isAlcohol: false, available: true, isVeg: false, floor: "both" },
  { id: "m129", name: "A Rich , Mild And Aromatic Thai Curry Cooked With Babycorn , Zuchhni , Brocooli, Carrpt Long Beans , Boild Potato , Bamboo Shoot Topped With Cheerry Tomato, Peanut", category: "food-mains", group: "food", price: 399, unit: "each", isAlcohol: false, available: true, isVeg: true, floor: "2nd-floor" },
  { id: "m130", name: "Massaman Curry Chicken With Jasmine Rice", category: "food-mains", group: "food", price: 425, unit: "each", isAlcohol: false, available: true, isVeg: false, floor: "2nd-floor" },
  // ─── BIRYANI & RICE ───
  { id: "m131", name: "Steam Rice", category: "food-biryani-rice", group: "food", price: 179, unit: "each", isAlcohol: false, available: true, isVeg: true, floor: "2nd-floor" },
  { id: "m132", name: "Jeera Rice", category: "food-biryani-rice", group: "food", price: 179, unit: "each", isAlcohol: false, available: true, isVeg: true, floor: "2nd-floor" },
  { id: "m133", name: "Curd Rice", category: "food-biryani-rice", group: "food", price: 229, unit: "each", isAlcohol: false, available: true, isVeg: true, floor: "2nd-floor" },
  { id: "m134", name: "Dal Kichdi", category: "food-biryani-rice", group: "food", price: 249, unit: "each", isAlcohol: false, available: true, isVeg: true, floor: "2nd-floor" },
  { id: "m135", name: "Palak Kichdi", category: "food-biryani-rice", group: "food", price: 249, unit: "each", isAlcohol: false, available: true, isVeg: true, floor: "2nd-floor" },
  { id: "m136", name: "Veg Biryani", category: "food-biryani-rice", group: "food", price: 349, unit: "each", isAlcohol: false, available: true, isVeg: true, floor: "2nd-floor" },
  { id: "m137", name: "Chicken Dum Biryani", category: "food-biryani-rice", group: "food", price: 401, unit: "each", isAlcohol: false, available: true, isVeg: false, floor: "2nd-floor" },
  { id: "m138", name: "Mutton Biryani", category: "food-biryani-rice", group: "food", price: 520, unit: "each", isAlcohol: false, available: true, isVeg: false, floor: "2nd-floor" },
  // ─── FRIED RICE & NOODLES ───
  { id: "m139", name: "Veg Fried Rice", category: "food-noodles", group: "food", price: 299, unit: "each", isAlcohol: false, available: true, isVeg: true, floor: "2nd-floor" },
  { id: "m140", name: "Egg Fried Rice", category: "food-noodles", group: "food", price: 285, unit: "each", isAlcohol: false, available: true, isVeg: false, floor: "2nd-floor" },
  { id: "m141", name: "Chicken Fried Rice", category: "food-noodles", group: "food", price: 359, unit: "each", isAlcohol: false, available: true, isVeg: false, floor: "2nd-floor" },
  { id: "m142", name: "Schezwan Veg Fried Rice -", category: "food-noodles", group: "food", price: 299, unit: "each", isAlcohol: false, available: true, isVeg: true, floor: "2nd-floor" },
  { id: "m143", name: "Schezwan Egg Fried Rice", category: "food-noodles", group: "food", price: 285, unit: "each", isAlcohol: false, available: true, isVeg: false, floor: "2nd-floor" },
  { id: "m144", name: "Schezwan Chicken Fried Rice", category: "food-noodles", group: "food", price: 359, unit: "each", isAlcohol: false, available: true, isVeg: false, floor: "2nd-floor" },
  { id: "m145", name: "Brunt Garlic Cilantro Fried Rice - Veg", category: "food-noodles", group: "food", price: 299, unit: "each", isAlcohol: false, available: true, isVeg: true, floor: "2nd-floor" },
  { id: "m146", name: "Brunt Garlic Cilantro Fried Rice - Egg", category: "food-noodles", group: "food", price: 285, unit: "each", isAlcohol: false, available: true, isVeg: false, floor: "2nd-floor" },
  { id: "m147", name: "Brunt Garlic Cilantro Fried Rice - Chicken", category: "food-noodles", group: "food", price: 359, unit: "each", isAlcohol: false, available: true, isVeg: false, floor: "2nd-floor" },
  { id: "m148", name: "Hakka Noodle - Veg", category: "food-noodles", group: "food", price: 299, unit: "each", isAlcohol: false, available: true, isVeg: true, floor: "2nd-floor" },
  { id: "m149", name: "Hakka Noodle - Egg", category: "food-noodles", group: "food", price: 285, unit: "each", isAlcohol: false, available: true, isVeg: false, floor: "2nd-floor" },
  { id: "m150", name: "Hakka Noodle - Chicken", category: "food-noodles", group: "food", price: 359, unit: "each", isAlcohol: false, available: true, isVeg: false, floor: "2nd-floor" },
  { id: "m151", name: "Schezwan Noodle - Veg", category: "food-noodles", group: "food", price: 299, unit: "each", isAlcohol: false, available: true, isVeg: true, floor: "2nd-floor" },
  { id: "m152", name: "Schezwan Noodle - Egg", category: "food-noodles", group: "food", price: 285, unit: "each", isAlcohol: false, available: true, isVeg: false, floor: "2nd-floor" },
  { id: "m153", name: "Schezwan Noodle - Chicken", category: "food-noodles", group: "food", price: 359, unit: "each", isAlcohol: false, available: true, isVeg: false, floor: "2nd-floor" },
  { id: "m154", name: "Brunt Garlic Cilantro Noodles - Veg", category: "food-noodles", group: "food", price: 299, unit: "each", isAlcohol: false, available: true, isVeg: true, floor: "2nd-floor" },
  { id: "m155", name: "Brunt Garlic Cilantro Noodles - Egg", category: "food-noodles", group: "food", price: 285, unit: "each", isAlcohol: false, available: true, isVeg: false, floor: "2nd-floor" },
  { id: "m156", name: "Brunt Garlic Cilantro Noodles Chicken", category: "food-noodles", group: "food", price: 359, unit: "each", isAlcohol: false, available: true, isVeg: false, floor: "2nd-floor" },
  // ─── BREADS ───
  { id: "m157", name: "Roti - Plain", category: "food-breads", group: "food", price: 55, unit: "each", isAlcohol: false, available: true, isVeg: true, floor: "2nd-floor" },
  { id: "m158", name: "Roti - Butter", category: "food-breads", group: "food", price: 65, unit: "each", isAlcohol: false, available: true, isVeg: true, floor: "2nd-floor" },
  { id: "m159", name: "Roti - Green Chilli", category: "food-breads", group: "food", price: 65, unit: "each", isAlcohol: false, available: true, isVeg: true, floor: "2nd-floor" },
  { id: "m160", name: "Naan - Plain", category: "food-breads", group: "food", price: 75, unit: "each", isAlcohol: false, available: true, isVeg: true, floor: "2nd-floor" },
  { id: "m161", name: "Naan - Butter", category: "food-breads", group: "food", price: 79, unit: "each", isAlcohol: false, available: true, isVeg: true, floor: "2nd-floor" },
  { id: "m162", name: "Naan - Garlic", category: "food-breads", group: "food", price: 79, unit: "each", isAlcohol: false, available: true, isVeg: true, floor: "2nd-floor" },
  { id: "m163", name: "Cheese Garlic Naan", category: "food-breads", group: "food", price: 125, unit: "each", isAlcohol: false, available: true, isVeg: true, floor: "2nd-floor" },
  { id: "m164", name: "Lachha Parantha - Plain", category: "food-breads", group: "food", price: 75, unit: "each", isAlcohol: false, available: true, isVeg: true, floor: "2nd-floor" },
  { id: "m165", name: "Lachha Parantha - Butter", category: "food-breads", group: "food", price: 79, unit: "each", isAlcohol: false, available: true, isVeg: true, floor: "2nd-floor" },
  { id: "m166", name: "Lachha Parantha - Pudina", category: "food-breads", group: "food", price: 79, unit: "each", isAlcohol: false, available: true, isVeg: true, floor: "2nd-floor" },
  { id: "m167", name: "Kulcha - Plain", category: "food-breads", group: "food", price: 59, unit: "each", isAlcohol: false, available: true, isVeg: true, floor: "2nd-floor" },
  { id: "m168", name: "Kulcha - Butter", category: "food-breads", group: "food", price: 69, unit: "each", isAlcohol: false, available: true, isVeg: true, floor: "2nd-floor" },
  // ─── DESSERTS ───
  { id: "m169", name: "Sizzling Brownie With Ice Cream", category: "food-desserts", group: "food", price: 399, unit: "each", isAlcohol: false, available: true, isVeg: true, costPrice: 43, floor: "both" },
  { id: "m170", name: "Coconut Caramel Custard", category: "food-desserts", group: "food", price: 299, unit: "each", isAlcohol: false, available: true, isVeg: true, floor: "both" },
  { id: "m171", name: "Pistachio Tres Laches", category: "food-desserts", group: "food", price: 299, unit: "each", isAlcohol: false, available: true, isVeg: true, costPrice: 55, floor: "both" },
  { id: "m172", name: "Tirsamisu Pull Me Up", category: "food-desserts", group: "food", price: 399, unit: "each", isAlcohol: false, available: true, isVeg: true, costPrice: 69, floor: "both" },
  { id: "m173", name: "Lotus Biscoff Cheese Cake", category: "food-desserts", group: "food", price: 399, unit: "each", isAlcohol: false, available: true, isVeg: true, floor: "both" },
  { id: "m174", name: "Chilli Gauva Ice Cream", category: "food-desserts", group: "food", price: 279, unit: "each", isAlcohol: false, available: true, isVeg: true, floor: "both" },
  { id: "m175", name: "Gilkond Ice Cream", category: "food-desserts", group: "food", price: 279, unit: "each", isAlcohol: false, available: true, isVeg: true, floor: "both" },
  { id: "m176", name: "Vanilla Ice Cream", category: "food-desserts", group: "food", price: 229, unit: "each", isAlcohol: false, available: true, isVeg: true, floor: "both" },
  // ─── CRAFT BEER ───
  { id: "m177", name: "Toit Tint Wit", category: "beer-craft", group: "beer-wine", price: 402, unit: "330ml", isAlcohol: true, available: true, servingSizes: {"s330":402,"s500":517,"pitcher":1380,"tower":2530} },
  { id: "m178", name: "Toit Hefeweizen", category: "beer-craft", group: "beer-wine", price: 410, unit: "330ml", isAlcohol: true, available: true, servingSizes: {"s330":410,"s500":530,"pitcher":1499,"tower":2650} },
  // ─── BEER & BREEZERS ───
  { id: "m179", name: "Cranberry", category: "beer", group: "beer-wine", price: 422, unit: "330ml", isAlcohol: true, available: true },
  { id: "m180", name: "Orange", category: "beer", group: "beer-wine", price: 422, unit: "330ml", isAlcohol: true, available: true },
  { id: "m181", name: "Jamaican Passion", category: "beer", group: "beer-wine", price: 422, unit: "330ml", isAlcohol: true, available: true },
  { id: "m182", name: "Watermellon", category: "beer", group: "beer-wine", price: 422, unit: "330ml", isAlcohol: true, available: true },
  { id: "m183", name: "Kingfisher Ultra Wit", category: "beer", group: "beer-wine", price: 400, unit: "330ml", isAlcohol: true, available: true },
  { id: "m184", name: "Kingfisher Ultra Max", category: "beer", group: "beer-wine", price: 460, unit: "330ml", isAlcohol: true, available: true },
  { id: "m185", name: "Hoegaarden", category: "beer", group: "beer-wine", price: 520, unit: "330ml", isAlcohol: true, available: true },
  { id: "m186", name: "Corona", category: "beer", group: "beer-wine", price: 570, unit: "330ml", isAlcohol: true, available: true },
  { id: "m187", name: "Heiniken", category: "beer", group: "beer-wine", price: 520, unit: "330ml", isAlcohol: true, available: true },
  { id: "m188", name: "Budwiser Magnum", category: "beer", group: "beer-wine", price: 460, unit: "330ml", isAlcohol: true, available: true },
  { id: "m189", name: "Budwiser Premium", category: "beer", group: "beer-wine", price: 400, unit: "330ml", isAlcohol: true, available: true },
  { id: "m190", name: "Kingfisher Ultra", category: "beer", group: "beer-wine", price: 400, unit: "330ml", isAlcohol: true, available: true },
  { id: "m191", name: "Tuborg", category: "beer", group: "beer-wine", price: 400, unit: "330ml", isAlcohol: true, available: true },
  { id: "m192", name: "Bro Code", category: "beer", group: "beer-wine", price: 480, unit: "330ml", isAlcohol: true, available: true },
  { id: "m193", name: "Boroka Gin & Tonic", category: "beer", group: "beer-wine", price: 450, unit: "330ml", isAlcohol: true, available: true },
  { id: "m194", name: "Panthera", category: "beer", group: "beer-wine", price: 480, unit: "330ml", isAlcohol: true, available: true },
  { id: "m195", name: "Budwiser Magnum", category: "beer", group: "beer-wine", price: 399, unit: "330ml", isAlcohol: true, available: true },
  { id: "m196", name: "Budwiser Preimum", category: "beer", group: "beer-wine", price: 379, unit: "330ml", isAlcohol: true, available: true },
  { id: "m197", name: "Kingfisher Ultra", category: "beer", group: "beer-wine", price: 600, unit: "330ml", isAlcohol: true, available: true },
  { id: "m198", name: "Kingfisher Ultra Max", category: "beer", group: "beer-wine", price: 380, unit: "330ml", isAlcohol: true, available: true },
  // ─── WINE & SPARKLING ───
  { id: "m199", name: "Chandon Brut", category: "wine", group: "beer-wine", price: 4025, unit: "bottle", isAlcohol: true, available: true },
  { id: "m200", name: "Sula Brut", category: "wine", group: "beer-wine", price: 4025, unit: "bottle", isAlcohol: true, available: true },
  { id: "m201", name: "Jacob Greek Red", category: "wine", group: "beer-wine", price: 690, unit: "glass", isAlcohol: true, available: true, bottlePrice: 3450 },
  { id: "m202", name: "Sula Red", category: "wine", group: "beer-wine", price: 575, unit: "glass", isAlcohol: true, available: true },
  { id: "m203", name: "Sula White", category: "wine", group: "beer-wine", price: 480, unit: "glass", isAlcohol: true, available: true },
  { id: "m204", name: "Sula Rose", category: "wine", group: "beer-wine", price: 517, unit: "glass", isAlcohol: true, available: true },
  // ─── SINGLE MALT ───
  { id: "m205", name: "Amruth Fusion", category: "spirits-single-malt", group: "spirits", price: 862, unit: "30ml", isAlcohol: true, available: true, bottlePrice: 17250 },
  { id: "m206", name: "Jack Daniels Single Barrle", category: "spirits-single-malt", group: "spirits", price: 920, unit: "30ml", isAlcohol: true, available: true, bottlePrice: 18400 },
  { id: "m207", name: "Glenlivet 12 Yrs", category: "spirits-single-malt", group: "spirits", price: 918, unit: "30ml", isAlcohol: true, available: true, bottlePrice: 18360 },
  { id: "m208", name: "Glenfiddich 12 Yrs", category: "spirits-single-malt", group: "spirits", price: 850, unit: "30ml", isAlcohol: true, available: true, bottlePrice: 17000 },
  { id: "m209", name: "Jura", category: "spirits-single-malt", group: "spirits", price: 810, unit: "30ml", isAlcohol: true, available: true, bottlePrice: 16200 },
  { id: "m210", name: "Laphroaig 10 Yrs", category: "spirits-single-malt", group: "spirits", price: 805, unit: "30ml", isAlcohol: true, available: true, bottlePrice: 16100 },
  { id: "m211", name: "Paul John Mithuna", category: "spirits-single-malt", group: "spirits", price: 2250, unit: "30ml", isAlcohol: true, available: true, bottlePrice: 45000 },
  { id: "m212", name: "Paul John Nirvana", category: "spirits-single-malt", group: "spirits", price: 529, unit: "30ml", isAlcohol: true, available: true, bottlePrice: 10580 },
  { id: "m213", name: "Paul John Brilliance", category: "spirits-single-malt", group: "spirits", price: 529, unit: "30ml", isAlcohol: true, available: true, bottlePrice: 10580 },
  // ─── SCOTCH & IMFL WHISKY ───
  { id: "m214", name: "Jw Blue Lable", category: "spirits-scotch", group: "spirits", price: 1700, unit: "30ml", isAlcohol: true, available: true, bottlePrice: 34000 },
  { id: "m215", name: "Jw Gold Lable", category: "spirits-scotch", group: "spirits", price: 918, unit: "30ml", isAlcohol: true, available: true, bottlePrice: 18360 },
  { id: "m216", name: "Jw Double Black", category: "spirits-scotch", group: "spirits", price: 902, unit: "30ml", isAlcohol: true, available: true, bottlePrice: 18040 },
  { id: "m217", name: "Chivas Regal", category: "spirits-scotch", group: "spirits", price: 823, unit: "30ml", isAlcohol: true, available: true, bottlePrice: 16460 },
  { id: "m218", name: "Jw Red Lable", category: "spirits-scotch", group: "spirits", price: 550, unit: "30ml", isAlcohol: true, available: true, bottlePrice: 11000 },
  { id: "m219", name: "Ballentine", category: "spirits-scotch", group: "spirits", price: 450, unit: "30ml", isAlcohol: true, available: true, bottlePrice: 9000 },
  { id: "m220", name: "Black And White", category: "spirits-scotch", group: "spirits", price: 410, unit: "30ml", isAlcohol: true, available: true, bottlePrice: 8200 },
  { id: "m221", name: "Teachers 50", category: "spirits-scotch", group: "spirits", price: 440, unit: "30ml", isAlcohol: true, available: true, bottlePrice: 8800 },
  { id: "m222", name: "Teachers Highland Cream", category: "spirits-scotch", group: "spirits", price: 370, unit: "30ml", isAlcohol: true, available: true, bottlePrice: 7400 },
  { id: "m223", name: "Black Dog Gold Reserve", category: "spirits-scotch", group: "spirits", price: 520, unit: "30ml", isAlcohol: true, available: true, bottlePrice: 10400 },
  { id: "m224", name: "100 Pipers", category: "spirits-scotch", group: "spirits", price: 410, unit: "30ml", isAlcohol: true, available: true, bottlePrice: 8200 },
  { id: "m225", name: "Blenders Pride", category: "spirits-scotch", group: "spirits", price: 330, unit: "30ml", isAlcohol: true, available: true, bottlePrice: 6600 },
  { id: "m226", name: "Black Bottle", category: "spirits-scotch", group: "spirits", price: 510, unit: "30ml", isAlcohol: true, available: true, bottlePrice: 10200 },
  { id: "m227", name: "Black Velvet", category: "spirits-scotch", group: "spirits", price: 460, unit: "30ml", isAlcohol: true, available: true, bottlePrice: 9200 },
  { id: "m228", name: "Dewars 12 Yrs", category: "spirits-scotch", group: "spirits", price: 690, unit: "30ml", isAlcohol: true, available: true, bottlePrice: 13800 },
  { id: "m229", name: "Dewars White Lable", category: "spirits-scotch", group: "spirits", price: 410, unit: "30ml", isAlcohol: true, available: true, bottlePrice: 8200 },
  { id: "m230", name: "Evan Williams", category: "spirits-scotch", group: "spirits", price: 500, unit: "30ml", isAlcohol: true, available: true, bottlePrice: 10000 },
  { id: "m231", name: "Jw Blonde", category: "spirits-scotch", group: "spirits", price: 550, unit: "30ml", isAlcohol: true, available: true, bottlePrice: 11000 },
  { id: "m232", name: "J&b Rare", category: "spirits-scotch", group: "spirits", price: 460, unit: "30ml", isAlcohol: true, available: true, bottlePrice: 9200 },
  { id: "m233", name: "Scottish Leader", category: "spirits-scotch", group: "spirits", price: 370, unit: "30ml", isAlcohol: true, available: true, bottlePrice: 7400 },
  { id: "m234", name: "Oak Smith", category: "spirits-scotch", group: "spirits", price: 317, unit: "30ml", isAlcohol: true, available: true, bottlePrice: 6340 },
  // ─── AMERICAN & IRISH WHISKEY ───
  { id: "m235", name: "Jack Daniels", category: "spirits-whiskey", group: "spirits", price: 719, unit: "30ml", isAlcohol: true, available: true, bottlePrice: 14380 },
  { id: "m236", name: "Jim Beam", category: "spirits-whiskey", group: "spirits", price: 550, unit: "30ml", isAlcohol: true, available: true, bottlePrice: 11000 },
  { id: "m237", name: "Jameson", category: "spirits-whiskey", group: "spirits", price: 559, unit: "30ml", isAlcohol: true, available: true, bottlePrice: 11180 },
  // ─── VODKA ───
  { id: "m238", name: "Greey Goose", category: "spirits-vodka", group: "spirits", price: 895, unit: "30ml", isAlcohol: true, available: true, bottlePrice: 17900 },
  { id: "m239", name: "Absolut", category: "spirits-vodka", group: "spirits", price: 460, unit: "30ml", isAlcohol: true, available: true, bottlePrice: 9200 },
  { id: "m240", name: "Stoli", category: "spirits-vodka", group: "spirits", price: 600, unit: "30ml", isAlcohol: true, available: true, bottlePrice: 12000 },
  { id: "m241", name: "Beluga", category: "spirits-vodka", group: "spirits", price: 1150, unit: "30ml", isAlcohol: true, available: true, bottlePrice: 23000 },
  { id: "m242", name: "Smirnoff Red", category: "spirits-vodka", group: "spirits", price: 400, unit: "30ml", isAlcohol: true, available: true, bottlePrice: 8000 },
  { id: "m243", name: "Mango Mirchi", category: "spirits-vodka", group: "spirits", price: 400, unit: "30ml", isAlcohol: true, available: true, bottlePrice: 8000 },
  { id: "m244", name: "Jamun", category: "spirits-vodka", group: "spirits", price: 400, unit: "30ml", isAlcohol: true, available: true, bottlePrice: 8000 },
  { id: "m245", name: "Lime", category: "spirits-vodka", group: "spirits", price: 400, unit: "30ml", isAlcohol: true, available: true, bottlePrice: 8000 },
  { id: "m246", name: "Roberto Cavali", category: "spirits-vodka", group: "spirits", price: 1150, unit: "30ml", isAlcohol: true, available: true, bottlePrice: 23000 },
  { id: "m247", name: "Zig Zag", category: "spirits-vodka", group: "spirits", price: 410, unit: "30ml", isAlcohol: true, available: true, bottlePrice: 5000 },
  // ─── GIN ───
  { id: "m248", name: "Bombay Sapphire", category: "spirits-gin", group: "spirits", price: 608, unit: "30ml", isAlcohol: true, available: true, bottlePrice: 12160 },
  { id: "m249", name: "Beefeater", category: "spirits-gin", group: "spirits", price: 510, unit: "30ml", isAlcohol: true, available: true, bottlePrice: 10200 },
  { id: "m250", name: "Great Indian Gin", category: "spirits-gin", group: "spirits", price: 550, unit: "30ml", isAlcohol: true, available: true, bottlePrice: 11000 },
  // ─── RUM ───
  { id: "m251", name: "Bacardi White", category: "spirits-rum", group: "spirits", price: 370, unit: "30ml", isAlcohol: true, available: true, bottlePrice: 7400 },
  { id: "m252", name: "Lemon", category: "spirits-rum", group: "spirits", price: 370, unit: "30ml", isAlcohol: true, available: true, bottlePrice: 7400 },
  { id: "m253", name: "Orange", category: "spirits-rum", group: "spirits", price: 370, unit: "30ml", isAlcohol: true, available: true, bottlePrice: 7400 },
  { id: "m254", name: "Old Monkk Dark", category: "spirits-rum", group: "spirits", price: 230, unit: "30ml", isAlcohol: true, available: true },
  { id: "m255", name: "Coffee", category: "spirits-rum", group: "spirits", price: 402, unit: "30ml", isAlcohol: true, available: true },
  // ─── TEQUILA ───
  { id: "m256", name: "Patron Silver", category: "spirits-tequila", group: "spirits", price: 1287, unit: "30ml", isAlcohol: true, available: true, bottlePrice: 25740 },
  { id: "m257", name: "Jose Cuervo Silver", category: "spirits-tequila", group: "spirits", price: 575, unit: "30ml", isAlcohol: true, available: true, bottlePrice: 2300 },
  { id: "m258", name: "Camino Gold", category: "spirits-tequila", group: "spirits", price: 450, unit: "30ml", isAlcohol: true, available: true, bottlePrice: 9240 },
  { id: "m259", name: "Camino Silver", category: "spirits-tequila", group: "spirits", price: 550, unit: "30ml", isAlcohol: true, available: true, bottlePrice: 11000 },
  { id: "m260", name: "Desmondji 51", category: "spirits-tequila", group: "spirits", price: 550, unit: "30ml", isAlcohol: true, available: true, bottlePrice: 11000 },
  // ─── BRANDY & COGNAC ───
  { id: "m261", name: "Hennessey Vsop", category: "spirits-brandy", group: "spirits", price: 805, unit: "30ml", isAlcohol: true, available: true, bottlePrice: 16100 },
  { id: "m262", name: "Morpheus", category: "spirits-brandy", group: "spirits", price: 330, unit: "30ml", isAlcohol: true, available: true, bottlePrice: 6600 },
  { id: "m263", name: "Mansion House", category: "spirits-brandy", group: "spirits", price: 270, unit: "30ml", isAlcohol: true, available: true, bottlePrice: 5400 },
  // ─── LIQUEURS ───
  { id: "m264", name: "Absente 49", category: "spirits-liqueur", group: "spirits", price: 450, unit: "30ml", isAlcohol: true, available: true, bottlePrice: 9000 },
  { id: "m265", name: "Jagermiester", category: "spirits-liqueur", group: "spirits", price: 800, unit: "30ml", isAlcohol: true, available: true, bottlePrice: 16000 },
  { id: "m266", name: "Jagermiester Orange", category: "spirits-liqueur", group: "spirits", price: 800, unit: "30ml", isAlcohol: true, available: true, bottlePrice: 16000 },
  { id: "m267", name: "Baileys Irish Cream", category: "spirits-liqueur", group: "spirits", price: 690, unit: "30ml", isAlcohol: true, available: true, bottlePrice: 13800 },
  { id: "m268", name: "Sambucca", category: "spirits-liqueur", group: "spirits", price: 450, unit: "30ml", isAlcohol: true, available: true, bottlePrice: 9000 },
  { id: "m269", name: "Kahlua Coffee Liqueur", category: "spirits-liqueur", group: "spirits", price: 450, unit: "30ml", isAlcohol: true, available: true, bottlePrice: 9000 },
  // ─── COCKTAILS ───
  { id: "m270", name: "Bull Frog", category: "cocktails", group: "cocktails", price: 850, unit: "glass", isAlcohol: true, available: true, pitcherPrice: 3000 },
  { id: "m271", name: "Long Island Ice Tea", category: "cocktails", group: "cocktails", price: 800, unit: "glass", isAlcohol: true, available: true, pitcherPrice: 2800 },
  { id: "m272", name: "Long Beach Ice Tea", category: "cocktails", group: "cocktails", price: 800, unit: "glass", isAlcohol: true, available: true, pitcherPrice: 2800 },
  { id: "m273", name: "Tequila Sunrise", category: "cocktails", group: "cocktails", price: 650, unit: "glass", isAlcohol: true, available: true },
  { id: "m274", name: "Margarita", category: "cocktails", group: "cocktails", price: 630, unit: "glass", isAlcohol: true, available: true },
  { id: "m275", name: "Martini", category: "cocktails", group: "cocktails", price: 600, unit: "glass", isAlcohol: true, available: true },
  { id: "m276", name: "Whisky Sour", category: "cocktails", group: "cocktails", price: 570, unit: "glass", isAlcohol: true, available: true },
  { id: "m277", name: "Sex On The Beach", category: "cocktails", group: "cocktails", price: 570, unit: "glass", isAlcohol: true, available: true },
  { id: "m278", name: "Cosmopolitan", category: "cocktails", group: "cocktails", price: 570, unit: "glass", isAlcohol: true, available: true },
  { id: "m279", name: "Pinacolada", category: "cocktails", group: "cocktails", price: 575, unit: "glass", isAlcohol: true, available: true },
  { id: "m280", name: "Mojito", category: "cocktails", group: "cocktails", price: 575, unit: "glass", isAlcohol: true, available: true },
  { id: "m281", name: "Daiquiri", category: "cocktails", group: "cocktails", price: 575, unit: "glass", isAlcohol: true, available: true },
  { id: "m282", name: "Mai Tai", category: "cocktails", group: "cocktails", price: 575, unit: "glass", isAlcohol: true, available: true },
  { id: "m283", name: "Cajun Kick", category: "cocktails", group: "cocktails", price: 600, unit: "glass", isAlcohol: true, available: true },
  { id: "m284", name: "Ginger War", category: "cocktails", group: "cocktails", price: 555, unit: "glass", isAlcohol: true, available: true },
  { id: "m285", name: "Basil Blast", category: "cocktails", group: "cocktails", price: 555, unit: "glass", isAlcohol: true, available: true },
  { id: "m286", name: "Daddy Hod", category: "cocktails", group: "cocktails", price: 555, unit: "glass", isAlcohol: true, available: true },
  // ─── MOCKTAILS ───
  { id: "m287", name: "Innocent Passion", category: "mocktails", group: "cocktails", price: 345, unit: "glass", isAlcohol: false, available: true },
  { id: "m288", name: "Cassis Cooler", category: "mocktails", group: "cocktails", price: 345, unit: "glass", isAlcohol: false, available: true },
  { id: "m289", name: "Funky Toffy", category: "mocktails", group: "cocktails", price: 345, unit: "glass", isAlcohol: false, available: true },
  { id: "m290", name: "Paradise Iceland", category: "mocktails", group: "cocktails", price: 345, unit: "glass", isAlcohol: false, available: true },
  { id: "m291", name: "Virgin Mojito", category: "mocktails", group: "cocktails", price: 345, unit: "glass", isAlcohol: false, available: true },
  { id: "m292", name: "Virgin Colada", category: "mocktails", group: "cocktails", price: 345, unit: "glass", isAlcohol: false, available: true },
  { id: "m293", name: "Fruit Punch", category: "mocktails", group: "cocktails", price: 345, unit: "glass", isAlcohol: false, available: true },
  { id: "m294", name: "Ice Tea", category: "mocktails", group: "cocktails", price: 345, unit: "glass", isAlcohol: false, available: true },
  { id: "m295", name: "Guava Mary", category: "mocktails", group: "cocktails", price: 345, unit: "glass", isAlcohol: false, available: true },
  // ─── SHOOTERS & FLAMERS ───
  { id: "m296", name: "Jager Bomb / Orange", category: "shooters", group: "cocktails", price: 800, unit: "30ml", isAlcohol: true, available: true },
  { id: "m297", name: "B52", category: "shooters", group: "cocktails", price: 550, unit: "30ml", isAlcohol: true, available: true },
  { id: "m298", name: "Kamakazi", category: "shooters", group: "cocktails", price: 430, unit: "30ml", isAlcohol: true, available: true },
  { id: "m299", name: "Death Note", category: "shooters", group: "cocktails", price: 430, unit: "30ml", isAlcohol: true, available: true },
  { id: "m300", name: "Get Laid", category: "shooters", group: "cocktails", price: 430, unit: "30ml", isAlcohol: true, available: true },
  { id: "m301", name: "Flaming Lamborgini", category: "shooters", group: "cocktails", price: 2500, unit: "30ml", isAlcohol: true, available: true },
  { id: "m302", name: "Hod On Fire", category: "shooters", group: "cocktails", price: 2500, unit: "30ml", isAlcohol: true, available: true },
  // ─── SOFT DRINKS & BEVERAGES ───
  { id: "m303", name: "Red Bull", category: "soft-drinks", group: "soft", price: 350, unit: "glass", isAlcohol: false, available: true },
  { id: "m304", name: "Ginger Ale", category: "soft-drinks", group: "soft", price: 170, unit: "glass", isAlcohol: false, available: true },
  { id: "m305", name: "Tonic Water", category: "soft-drinks", group: "soft", price: 170, unit: "glass", isAlcohol: false, available: true },
  { id: "m306", name: "Diet Coke", category: "soft-drinks", group: "soft", price: 150, unit: "glass", isAlcohol: false, available: true },
  { id: "m307", name: "Fresh Lime Soda / Water", category: "soft-drinks", group: "soft", price: 200, unit: "glass", isAlcohol: false, available: true },
  { id: "m308", name: "Canned Juices", category: "soft-drinks", group: "soft", price: 170, unit: "glass", isAlcohol: false, available: true },
  { id: "m309", name: "Coke", category: "soft-drinks", group: "soft", price: 100, unit: "glass", isAlcohol: false, available: true },
  { id: "m310", name: "Sprite", category: "soft-drinks", group: "soft", price: 100, unit: "glass", isAlcohol: false, available: true },
  { id: "m311", name: "Soda", category: "soft-drinks", group: "soft", price: 75, unit: "glass", isAlcohol: false, available: true },
  { id: "m312", name: "Fresh Lime Water", category: "soft-drinks", group: "soft", price: 150, unit: "glass", isAlcohol: false, available: true },
  { id: "m313", name: "Fresh Lime Soda", category: "soft-drinks", group: "soft", price: 200, unit: "glass", isAlcohol: false, available: true },
  { id: "m314", name: "Water 500ml", category: "soft-drinks", group: "soft", price: 35, unit: "bottle", isAlcohol: false, available: true },
];

export const CATEGORY_LABELS: Record<MenuCategory, string> = {
  "food-soups": "SOUPS",
  "food-salads": "SALADS",
  "food-bar-bites": "BAR BITES & CHAAT",
  "food-chargrilled": "CHARGRILLED APPETIZERS",
  "food-platters": "PLATTERS",
  "food-oriental": "ORIENTAL",
  "food-international": "INTERNATIONAL",
  "food-pasta-pizza": "PASTA & PIZZA",
  "food-coastal": "COASTAL",
  "food-mains": "MAIN COURSE",
  "food-biryani-rice": "BIRYANI & RICE",
  "food-noodles": "FRIED RICE & NOODLES",
  "food-breads": "BREADS",
  "food-desserts": "DESSERTS",
  "beer-craft": "CRAFT BEER",
  "beer": "BEER & BREEZERS",
  "wine": "WINE & SPARKLING",
  "spirits-single-malt": "SINGLE MALT",
  "spirits-scotch": "SCOTCH & IMFL WHISKY",
  "spirits-whiskey": "AMERICAN & IRISH WHISKEY",
  "spirits-vodka": "VODKA",
  "spirits-gin": "GIN",
  "spirits-rum": "RUM",
  "spirits-tequila": "TEQUILA",
  "spirits-brandy": "BRANDY & COGNAC",
  "spirits-liqueur": "LIQUEURS",
  "cocktails": "COCKTAILS",
  "mocktails": "MOCKTAILS",
  "shooters": "SHOOTERS & FLAMERS",
  "soft-drinks": "SOFT DRINKS & BEVERAGES",
};

export const GROUP_LABELS: Record<MenuCategoryGroup, string> = {
    spirits: "Spirits",
    "beer-wine": "Beer & Wine",
    cocktails: "Cocktails & Mocktails",
    soft: "Soft Drinks",
    food: "Food",
  };

export const GROUP_CATEGORIES: Record<MenuCategoryGroup, MenuCategory[]> = {
    spirits: ["spirits-single-malt", "spirits-scotch", "spirits-whiskey", "spirits-vodka", "spirits-gin", "spirits-rum", "spirits-tequila", "spirits-brandy", "spirits-liqueur"],
    "beer-wine": ["beer-craft", "beer", "wine"],
    cocktails: ["cocktails", "mocktails", "shooters"],
    soft: ["soft-drinks"],
    food: ["food-soups", "food-salads", "food-bar-bites", "food-chargrilled", "food-platters", "food-oriental", "food-international", "food-pasta-pizza", "food-coastal", "food-mains", "food-biryani-rice", "food-noodles", "food-breads", "food-desserts"],
  };

export function searchMenu(query: string): MenuItem[] {
    if (!query.trim()) return MENU_ITEMS.filter(i => i.available);
    const q = query.toLowerCase();
    return MENU_ITEMS.filter(
      (i) => i.available && (
        i.name.toLowerCase().includes(q) ||
        (CATEGORY_LABELS[i.category] || "").toLowerCase().includes(q)
      )
    );
  }

  export function getItemsByGroup(group: MenuCategoryGroup): MenuItem[] {
    const cats = GROUP_CATEGORIES[group] || [];
    return MENU_ITEMS.filter((i) => i.available && cats.includes(i.category));
  }

  export function getItemsByCategory(category: MenuCategory): MenuItem[] {
    return MENU_ITEMS.filter((i) => i.available && i.category === category);
  }
  