// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/hod-wallet-history/Timeline.tsx": () => import("../components/mockups/hod-wallet-history/Timeline.tsx")
};
